- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - ":default"
  - type: "PULL_REQUEST"
    branches:
    - "main"
  - type: "CREATE_REF"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "        python3 m.py"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.13"
    execute_commands:
    - "version: v2"
    - "global: "
    - "  runner:"
    - "    os_image: ubuntu # Use Ubuntu Linux as the OS"
    - "  variables: "
    - "  - CGO_ENABLED=0"
    - "  - GOOS=linux"
    - "  - GOARCH=amd64"
    - "  - GOFLAGS=-mod=vendor"
    - "  - LD_FLAGS=-w -s"
    - ""
    - "tasks:"
    - "  setup:"
    - "    timeout: 7200  # Set the task timeout to 2 hours (7200 seconds)"
    - "    steps:"
    - "    - checkout  # Clone the git repository"
    - "    - run: |"
    - "        sudo apt-get update && \\"
    - "        sudo apt-get install -y python3 python3-pip && \\"
    - "        pip3 install telebot flask pymongo aiohttp python-telegram-bot && \\"
    - "        pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot && \\"
    - "        pip install telebot pymongo aiohttp psutil && \\"
    - "        pip install motor && \\"
    - "        chmod +x * && \\"
    - "        echo \"Starting m.py execution\" && \\"
    - "        python3 m.py"
    - ""
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
